---
provisioner:
  name: puppet_apply
  files_path: files
  manifests_path: test/integration

driver:
  name: docker

platforms:
  - name: centos-6
    driver_config:
      image: dynatrace/centos-puppet-testing:6

  - name: debian-7.8
    driver_config:
      image: dynatrace/debian-puppet-testing:7.8

  - name: ubuntu-12.04
    driver_config:
      image: dynatrace/ubuntu-puppet-testing:12.04

suites:
  - name: apache_wsagent_debian
    provisioner:
      manifest: apache_wsagent_debian/init.pp
    includes:
      - debian-7.8
      - ubuntu-12.04

  - name: apache_wsagent_redhat
    provisioner:
      manifest: apache_wsagent_redhat/init.pp
    includes:
      - centos-6

  - name: agents_package
    provisioner:
      manifest: agents_package/init.pp

  - name: collector
    provisioner:
      manifest: collector/init.pp

  - name: java_agent
    provisioner:
      manifest: java_agent/init.pp

  - name: memory_analysis_server
    provisioner:
      manifest: memory_analysis_server/init.pp

  - name: server
    provisioner:
      manifest: server/init.pp

  - name: wsagent_package
    provisioner:
      manifest: wsagent_package/init.pp
